name: Leech Bot 4

on:
  push:
  workflow_dispatch:
   
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Cleanup & Storage 75GB wait for the 7 minutes
        uses: rokibhasansagar/slimhub_actions@main
      
      - name: Clone Mirror Repository
        run: |
          wget https://drive.nanthakps.workers.dev/0:/Others/Tamilarockers/leech-bot-4.zip && unzip leech-bot-4.zip -d source

      - name: Compile Docker
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t bot

      - name: Deploy Bot is 240 Minutes on Runing
        continue-on-error: true
        timeout-minutes: 240
        run: |
          docker run --privileged --rm -i bot
